### ISSUE TITLE
Opening sound options in the instrument test tab makes it stop working

### ISSUE THREAD

**Issue by PhoenixBound** [PKHackers/ebmused#25]
Ran into this minor issue while poking around and making sure some edits I made were working correctly. Reproduction steps:

* Open an EarthBound ROM
* Choose a song
* Go to the "Instruments" tab and choose an instrument. I chose "Hospital" and selected instrument 18 (the noise instrument).
* Click around or press the relevant keyboard keys to play notes. Observe that it works correctly.
* Go to Options --> Sound options in the menu bar at the top
* Without changing anything, click Cancel
* Click around now again. No notes make sound.
* Try switching to a different instrument. Now the instrument test rectangle stops responding to user input, until you switch to another tab and back.

**Comment by ChrisBlueStone** [comment]
This issue seems fixed with PR #53 so I'm closing it.
